name: Build MASM DLL

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v3

      # (Optional) if you need a specific tool-set, you can still use vswhere
      # Here we just let VC++ tools autoload on GitHub’s image.

      - name: Build CMake + MASM + MSBuild (x64)
        shell: pwsh
        run: |
          cmake `
            -S src\main\windows-x64-asm `
            -B build `
            -G "Visual Studio 17 2022" `
            -A x64 `
            -DCMAKE_BUILD_TYPE=Release `
            -DCMAKE_C_FLAGS_DEBUG="" `
            -DCMAKE_C_FLAGS_RELEASE=""


          cmake --build build --config Release
